### PR TITLE
Migrating to Meson build system - with cleaner commits

### LINKED ISSUE #4: Use the Meson build system
This would get us rid of a lot of autotools-based stuff, and would (I guess) simplify the project.

### PR DESCRIPTION
**Pull request by blu-base**
This is an improved PR from #9, still referencing to #4.

### CODE REVIEW

**Comment by tshikaboom** [comment]
This seems really cool, having looked around so far. A few thoughts and comments:

I see that debugging is enabled by default, instead of having to explicitly do `./configure --enable-debugging` with Autotools. Reading the Meson manual gives me the impression that this is something that is warranted by the build system by default, and one would have to explicitly do something extra for "release" builds (either compiling with no debug symbols, or compiling the symbols into separate files) This is fine :) just writing down my thoughts.

There's also some indentation nits here and there, but I won't keep you accountable for this :)

One thing that's changed, though, is that we had `-Werror` and all the paranoiac options enabled by default with Autotools. Could you do something to that effect, at least in default builds? I'm not sure where to define  `-Werror` as it is only one compiler option, it seems overkill to do it in `meson_options.txt` although I could be wrong. I see the paranoiac options can be enabled from there though, which makes sense as this defines a whole list of compiler checks in `meson.build`.

About the three `TODO`s:
- I looked at the header include tests (`have_stdint` and `have_inttypes`). I think these can be removed, as the cpp references I've skimmed tell me that these headers exist from C++11, and that is what we use by default anyway. I've removed these checks locally and it seems to work, could you do it too and confirm you get the same results?
- The library version, as I can see, can only be defined when we use the `shared_library()` target type in `src/lib`. Do we need a static library? Right now, the output is a simple `libone.so` (without a soversion set in the name) in the build directory which kind of seems dangerous if we'd get any programs using this library as an external dependency in the future. What are your thoughts about this?
- As for the TODO part where we should use `summary()`, I'll try to do that this evening or tomorrow to get my hands dirty :)

I'll make a separate issue on the Windows part of things once this gets merged, I think it's low priority enough at the moment, so it doesn't keep us blocked on other things. (I was thinking of getting rid of the `cc` C compiler part of the build definitions, as we use cpp, but that may or may not have effect on the Windows part of things, I don't know)

By the way, you did the grunt work of actually reading the Autotools files and finding ways to port functionality over to this, kudos for this :) this is some thankless work!

**Comment by blu-base** [comment]
> I see that debugging is enabled by default, instead of having to explicitly do `./configure --enable-debugging` with Autotools. 
Reading the Meson manual gives me the impression that this is something that is warranted by the build system by default, and one would have to explicitly do something extra for "release" builds (either compiling with no debug symbols, or compiling the symbols into separate files) This is fine :) just writing down my thoughts.

You are right, debug is by default set true, so it does not need to be explicitly set. I'll remove it from the project declaration.

> One thing that's changed, though, is that we had `-Werror` and all the paranoiac options enabled by default with Autotools. Could you do something to that effect, at least in default builds? I'm not sure where to define `-Werror` as it is only one compiler option, it seems overkill to do it in `meson_options.txt` although I could be wrong. I see the paranoiac options can be enabled from there though, which makes sense as this defines a whole list of compiler checks in `meson.build`.

This falls in the same category as the debug option. There is a built-in option for werror; so it does not need to be declared in meson_options. As reference: [the respective manual page](https://mesonbuild.com/Builtin-options.html).

I'll set werror and the other warning options explicitly true in the next commit.

> 
> There's also some indentation nits here and there, but I won't keep you accountable for this :)

Oh, yeah, i guess i haven't declared tab expansion for meson.build files yet... I'll recheck the build files.

> 


> About the three `TODO`s:
> looked at the header include tests (`have_stdint` and `have_inttypes`). I think these can be removed, as the cpp references I've skimmed tell me that these headers exist from C++11, and that is what we use by default anyway. I've removed these checks locally and it seems to work, could you do it too and confirm you get the same results?

I assumed this was task better to be separated into another PR. I'll test it too, and remove the respective parts if it works for me too.


> The library version, as I can see, can only be defined when we use the `shared_library()` target type in `src/lib`. Do we need a static library? Right now, the output is a simple `libone.so` (without a soversion set in the name) in the build directory which kind of seems dangerous if we'd get any programs using this library as an external dependency in the future. What are your thoughts about this?

This is where i had no clue. Other meson-based projects also explicitly defined a libtool-compatible name, but others did not. I also don't know about the difficulties of bundling a libraries... So, I'll take any suggestion how we should label it.

EDIT: i also declared libone to be a "library"---not specifically a shared library---so the build system/user can decide whether a shared or static library is needed.

> As for the TODO part where we should use `summary()`, I'll try to do that this evening or tomorrow to get my hands dirty :)

This is where i got lazy...

> I'll make a separate issue on the Windows part of things once this gets merged, I think it's low priority enough at the moment, so it doesn't keep us blocked on other things. (I was thinking of getting rid of the `cc` C compiler part of the build definitions, as we use cpp, but that may or may not have effect on the Windows part of things, I don't know)

I agree, this can be a problem for later.

> By the way, you did the grunt work of actually reading the Autotools files and finding ways to port functionality over to this, kudos for this :) this is some thankless work!

meson is much more familar to me than autotools since i have been using cmake more often... I was trying to write a test with the autotools setup and spend like an hour to link the test executable with the compiled library... without success. So I am looking forward to not having as many issues.


I also just now learned that there is this derived library generator for librevenge. Maybe with some further work, this could be pushed upstream.

**Comment by blu-base** [comment]
There is one more bug fixed in the above commits. `doxygen` did not include `libone.h` and `ONEDocument.h` before.
Moreover, the default `header.html.in` and `footer.html.in` do not seem to work properly for me. That's why i disabled them for now.

**Comment by blu-base** [comment]
One more observation, if the conversion tools seem to fall in an endless loop. When i build them with debug symbols, they are working fine. I did not investigate yet, why this is the case.

**Comment by tshikaboom** [comment]
> Moreover, the default `header.html.in` and `footer.html.in` do not seem to work properly for me. That's why i disabled them for now.

I looked at this, it seems that without these (header and footer) I get the nice-looking navigation sidebar, whereas before it had never shown up in the docs (this is nice, btw!). It seems to be better as is, I don't know if it's worth putting in a lot of time to get these working, as I even don't know how this stuff works...
Maybe worth an issue for afterwards, to keep track of this, and keep this commented for now (which is what your commit does)

**Comment by tshikaboom** [comment]
I did the `summary()` part and will look into the infinite loop. Will make a PR against your branch so you get to review this too.

Also, it seems that some of the paranoic options weren't actually enabled in the Autotools build... :) there's lots of missing `case` statements as reported by the compiler and some other type-related nits, I'll have a go at it too (the ultimate objective would be not to merge something that breaks the build).
(edit: I'll make a separate PR to merge before this one, to still try to separate stuff logically...)

Let's see if these warnings are too heavy as we go on, some of them could be switched off in the future if it gets too annoying.

**Comment by tshikaboom** [comment]
So, I created #11 for the paranoiac compiler fallout introduced by this.
Also #12 should resolve the infinite loop problem when not compiled in debug mode, can you check if that works for you?

Oh, and I also pushed a PR (https://github.com/blu-base/libone/pull/1) merge'able to this PR, making use of the `summary()` Meson built-in. :)

At this point, the big thing left would be to figure out the `soversion` of the library, I'll have a dig at it later, either this evening or tomorrow.

Otherwise, I'd be in favor of doing investigation issues about the documentation header/footers (since it basically seems to work at this point, even without the headers/footers) and Windows portability.

Did I forget anything else?

**Comment by tshikaboom** [comment]
> At this point, the big thing left would be to figure out the `soversion` of the library, I'll have a dig at it later, either this evening or tomorrow.

I found a way to do it! It seems to be a one-liner fix in Meson.
```
[oskar@hsw-arch libone-meson]$ ll builddir/src/lib/
kokku 3124
drwxr-xr-x 2 oskar oskar    4096  1. aug   19:00 91be6cf@@one@sha
lrwxrwxrwx 1 oskar oskar      11  1. aug   19:00 libone.so -> libone.so.0
lrwxrwxrwx 1 oskar oskar      16  1. aug   19:00 libone.so.0 -> libone.so.0.0.90
-rwxr-xr-x 1 oskar oskar 3191040  1. aug   19:00 libone.so.0.0.90
```
The fix is in my PR to this branch.

**Comment by blu-base** [comment]
> Also, it seems that some of the paranoic options weren't actually enabled in the Autotools build... :) there's lots of missing `case` statements as reported by the compiler and some other type-related nits, I'll have a go at it too (the ultimate objective would be not to merge something that breaks the build).
> (edit: I'll make a separate PR to merge before this one, to still try to separate stuff logically...)
> 
> Let's see if these warnings are too heavy as we go on, some of them could be switched off in the future if it gets too annoying.

Ok. I set the wparanoic option in `meson_options.txt` to true by default after you asked. I would revert this option back to false, and recheck which was actually set in the autotools.

I think, i had checked that once; that's why I set it to off by default initially.
I'll revert this option's defaults. Then we can make sure this PR is not a breaking change.

**Comment by blu-base** [comment]
> I found a way to do it! It seems to be a one-liner fix in Meson.

Awesome! That's an enjoyable solution =)

**Comment by blu-base** [comment]
Regarding the previous build options, the following section declares the respective compiler warings:

```
# ================
# Check for cflags
# ================
AC_ARG_ENABLE([werror],
    [AS_HELP_STRING([--disable-werror], [Treat all warnings as errors, usefull for development])],
    [enable_werror="$enableval"],
    [enable_werror=yes]
)
```
```
AC_ARG_ENABLE([weffc],
    [AS_HELP_STRING([--disable-weffc], [ Disable -Weffc++ warnings, usefull when using an old version of gcc or of boost])],
    [enable_weffc="$enableval"],
    [enable_weffc=yes]
)
AC_ARG_ENABLE([wparanoic],
    [AS_HELP_STRING([--enable-wparanoic], [Enable a lot of warnings...])],
    [enable_wparanoic="$enableval"],
    [enable_wparanoic=no]
)
```

Citing the manual on `AC_ARG_ENABLE`:

`Macro: AC_ARG_ENABLE (feature, help-string, [action-if-given], [action-if-not-given])`
It becomes clear that the last argument defines the default value.

For us, this means the library had the following default values:
- werror: true
- weffc: true
- wparanoic: false
- debug: false
- with_tests: true
- with_docs: true
- with_tools: true

The last commits(82ba789) makes the two build-systems compatible regarding their default values. 
For ease of use, i added a line on how to make this option active into the `HACKING` file.

**Comment by tshikaboom** [comment]
After having had a go at installing the directory tree to `/opt`, I think we're close to (or at) a merge. At least, from a functional point of view, we've got
- the dynamic library with its soname
- the headers (ONEDocument.h and libone.h)
- the pkg-config file
- the two converters `one2raw` and `one2svg`

There's one last nitpick though which I found when comparing the generated tree with what's installed on my computer. I saw that libmspub and libvisio install their headers in `${includedir}/${libraryname}-${version}/${libraryname}/`, which would translate to `/usr/include/libvisio-0.1/libvisio/` on my machine. (We're missing the `libone-0.0` part here)
I guess that's good practice wrt. header versioning, although I'm not sure if it's worthwhile doing this at this stage.. Do you have any opinions on this? I'm not terribly torn on either side of the argument...

**Comment by blu-base** [comment]
Thanks for your thorough review! i missed that part, too...
You are right, it would be best to conform with the other libraries in that respect.

4c77798 corrected that directory name.
the `install_headers` command contained the respective name for the installed include directory.

**Comment by tshikaboom** [comment]
Hey, let's do this then :)

We'll figure out the rest on the way, at least I can't think of any other things that would block this.

:+1:

**Pull request merged**
